#!/bin/bash
set -eu

rids=(`relation-ids fuel-master`)
if [ -n "${rids[*]+x}" ]; then
  rid=${rids[0]}
  if [ -z "${rid}" ]; then exit; fi
  roles=`config-get roles`
  relation-set -r $rid roles="$roles"
  storage_iface=`config-get storage-iface`
  storage_ip=''
  if [[ -n "$storage_iface" ]] ; then
    storage_ip=`ifconfig "$storage_iface" | awk '/inet addr/{print $2}' | sed 's/addr://'`
    relation-set -r $rid storage_ip="$storage_ip"
  fi
  juju-log "Roles: $roles, Storage address: $storage_ip"
fi
