#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "Fuel-master relation triggered on ${JUJU_REMOTE_UNIT}"

status-set maintenance

my_unit=`convert-name $JUJU_UNIT_NAME`
stage=`relation-get stage`
if [ -n "$stage" ]; then
    timestamp=`relation-get timestamp-$my_unit`
    if [ -z "$timestamp" ] ; then
        timestamp='0'
    fi
    if (( timestamp == 0 )); then
        setup
    fi
    parse_tasks
    mkdir -p /var/lib/hiera
    echo "$node_yaml" > /var/lib/hiera/defaults.yaml
    for puppet in ${!puppet_stage_map[*]}; do
        if (( puppet_stage_map[$puppet] == stage )); then
            juju-log "Executing puppet $puppet on stage $stage"
            exec_puppet $puppet
        fi
    done
    (( ++timestamp ))
    roles=`config-get roles`
    relation-set roles="$roles"
    relation-set "timestamp-$my_unit"=$timestamp
    juju-log "Node $JUJU_UNIT_NAME is ready to move to next stage, timestamp: $timestamp"
else
    status-set active
fi
