#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "Fuel-master relation joined on ${JUJU_REMOTE_UNIT}"

hostname=`hostname`
roles=`config-get roles`
storage_iface=`config-get storage-iface`
storage_ip=''
if [[ -n "$storage_iface" ]] ; then
  storage_ip=`ifconfig "$storage_iface" | awk '/inet addr/{print $2}' | sed 's/addr://'`
fi

relation-set storage_ip="$storage_ip"
relation-set roles="$roles"
relation-set hostname=$hostname

juju-log "Hostname: $hostname, Roles: $roles, Storage address: $storage_ip"
