#!/bin/bash

apt-get install -fy puppet git haproxy
puppet module install puppetlabs-firewall
puppet module install puppetlabs-stdlib
puppet module install puppetlabs-inifile
puppet module install puppetlabs-concat
puppet module install cloudscaling-scaleio_openstack
puppet module install cloudscaling-scaleio

pushd /root
rm -rf fuel-plugin-scaleio
branch=`config-get branch-name`
git clone https://github.com/openstack/fuel-plugin-scaleio.git
cd fuel-plugin-scaleio
git checkout $branch

# remove gateway from tasks.yaml
# it tries to install haproxy but 'ocf' package is absent
if [ -f tasks.yaml ]; then 
    mv tasks.yaml tasks.yaml.bak
    cat tasks.yaml.bak | sed -e '/gateway/{n;N;N;d}' | tac | sed -e '/gateway/{N;N;N;N;d}' | tac > tasks.yaml
fi

# hack to avoid problems at haproxy configuring stage
# mkdir -p /etc/haproxy/conf.d

popd

my_dir="$(dirname "$0")"
cp "$my_dir/../files/hiera.yaml" /etc/puppet
cp -r "$my_dir/../files/modules" /etc/puppet
