#!/bin/bash

apt-get install -fy puppet git haproxy
puppet module install puppetlabs-firewall
puppet module install puppetlabs-stdlib
puppet module install puppetlabs-inifile
puppet module install puppetlabs-concat
puppet module install --version "<0.5.0" cloudscaling-scaleio_openstack
puppet module install --version "<0.5.0" cloudscaling-scaleio

pushd /root
rm -rf fuel-plugin-scaleio
git clone https://github.com/cloudscaling/fuel-plugin-scaleio.git
cd fuel-plugin-scaleio

# remove gateway from tasks.yaml
# it tries to install haproxy but 'ocf' package is absent
if [ -f tasks.yaml ]; then 
    mv tasks.yaml tasks.yaml.bak
    cat tasks.yaml.bak | sed -e '/gateway/{n;N;N;d}' | tac | sed -e '/gateway/{N;N;N;N;d}' | tac > tasks.yaml
fi

# hack to avoid problems at haproxy configuring stage
# mkdir -p /etc/haproxy/conf.d

popd

# TODO: remove when packages will be in official repo
apt_repo=`config-get scaleio-apt-repo`
if [ -n "$apt_repo" ] ; then
  if wget -q --output-document=/root/repo.key $apt_repo/repo.key ; then
    apt-key add /root/repo.key
  fi

  cat 2>/dev/null <<EOF > /etc/apt/sources.list.d/repo.list
deb $apt_repo/ubuntu trusty main
deb-src $apt_repo/ubuntu trusty main
EOF

  apt-get -qq update
fi

my_dir="$(dirname "$0")"
cp "$my_dir/../files/hiera.yaml" /etc/puppet
cp -r "$my_dir/../files/modules" /etc/puppet
