options:
    deploy:
        type: string
        default: ""
        description: "Trigger to start new deployment. To be replaced with action later. Change value to trigger."
    storage-pools:
        type: string
        default: "default"
        description: "Storage pools"
    device-paths:
        type: string
        default: "/dev/sdb"
        description: "Device paths"
    protection-domain:
        type: string
        default: "default"
        description: "Protection domain"
    password:
        type: string
        default: "Default_password"
        description: "Password"
    sds-on-controller:
        type: string
        default: "true"
        description: "Is SDS on controller"
    facters:
        type: string
        default: "/root/fuel-plugin-scaleio/deployment_scripts/puppet/modules/scaleio_fuel/lib/facter:/etc/puppet/modules/scaleio_openstack/lib/facter"
        description: "Facters to set up before calling puppets"
    modules-path:
        type: string
        default: "/etc/puppet/modules"
        description: "Path to puppet modules"
    manifests-path:
        type: string
        default: "/root/fuel-plugin-scaleio/deployment_scripts/puppet/manifests"
        description: "Puppet manifests path"
    skip-checks:
        type: string
        default: "false"
        description: "Skip platform validation checks"
    zero-padding:
        type: string
        default: "false"
        description: "Zero padding: false / true"
    checksum-mode:
        type: string
        default: "false"
        description: "Checksum mode: false / true"
    scanner-mode:
        type: string
        default: "false"
        description: "Scanner mode: false / true"
    spare-policy:
        type: string
        default: "10"
        description: "Spare percentage: %"
    capacity-high-alert-threshold:
        type: string
        default: "80"
        description: "Capacity high priority alert 0-99"
    capacity-critical-alert-threshold:
        type: string
        default: "90"
        description: "Capacity critical priority alert 0-99"
    rfcache-devices:
        type: string
        default: ""
        description: "XtremCache devices, /dev/sdb,/dev/sdc"
    cached-storage-pools:
        type: string
        default: ""
        description: "XtremCache storage pools"
    branch-name:
        type: string
        default: "master"
        description: "Branch of fuel-plugin-scaleio"
    protection-domain-nodes:
        type: string
        default: "100"
        description: "Maximum number of nodes in one protection domain"
    metadata-enabled:
        type: string
        default: "true"
        description: "ScaleIO enabled."
