options:
  roles:
    type: string
    default: "controller"
    description: "Space separated list of fuel roles"
  branch-name:
    type: string
    default: "master"
    description: "Branch of fuel-plugin-scaleio"
  storage-iface:
    type: string
    default: ""
    description: "Interface to use for SDS-SDC communicaton."

