options:
  roles:
    type: string
    default: "controller"
    description: "Space separated list of fuel roles"
  scaleio-apt-repo:
    type: string
    default: "http://scaleio-packages.s3-website-us-east-1.amazonaws.com"
    description: |
      Optional. URL of apt repo where charm can find ScaleIO packages.
  branch-name:
    type: string
    default: "master"
    description: "Branch of fuel-plugin-scaleio"
  storage-iface:
    type: string
    default: ""
    description: "Interface to use for SDS-SDC communicaton."

