#!/bin/bash
set -eu

my_dir="$(dirname "$0")"

declare stages=()
stage_count=0
facters=`config-get facters`
manifests_path=`config-get manifests-path`

function parse_tasks {
    if [[ -f "$manifests_path/../../../deployment_tasks.yaml" ]]; then
        stage_array=(`python ${my_dir}/parse_deployment_tasks.py --stages --file $manifests_path/../../../deployment_tasks.yaml`)
    else
        stage_array=(`grep stage $manifests_path/../../../tasks.yaml | cut -d "/" -f 2`)        
    fi
    declare -A stage_hash=()
    for stage in ${stage_array[*]}; do
        stage_hash[$stage]=''
    done
    stages=(`printf "%s\n" ${!stage_hash[*]} | sort -n`)
    stage_count=${#stages[*]}
    juju-log "Stages: ${stages[*]}"
}

node_yaml=''
rids=(`relation-ids fuel-master`)

declare -A node_roles=()
declare -A node_ips=()
declare -A node_storage_ips=()
declare -A node_names=()
management_vip='127.0.0.1'

function convert-name {
  echo ${1//[-\/]/_}
}

function retrieve-nodes-info {
    for rid in $rids; do
        units=`relation-list -r $rid`
        for unit in $units; do
            local roles=`relation-get -r $rid roles $unit`
            local ip=`relation-get -r $rid private-address $unit`
            local storage_ip=`relation-get -r $rid storage_address $unit`
            local hostname=`relation-get -r $rid hostname $unit`
            if [ -z "$roles" ]; then exit; fi
            if [[ "$roles" =~ controller ]]; then
                management_vip=$ip
            fi
            node_roles[$unit]="$roles"
            node_ips[$unit]="$ip"
            if [[ -n $storage_ip ]] ; then
              node_storage_ips[$unit]="$storage_ip"
            else
              node_storage_ips[$unit]="$ip"
            fi
            node_names[$unit]="$hostname"
        done
    done
}

function prepare_node_yaml {
    if [[ -z ${rids[*]+x} ]]; then exit 0; fi

    retrieve-nodes-info

    juju-log "`declare -p node_roles`"
    juju-log "`declare -p node_ips`"
    juju-log "`declare -p node_storage_ips`"

    storage_pools=`config-get storage-pools`
    device_paths=`config-get device-paths`
    protection_domain=`config-get protection-domain`
    password=`config-get password`
    sds_on_controller=`config-get sds-on-controller`
    skip_checks=`config-get skip-checks`
    zero_padding=`config-get zero-padding`
    checksum_mode=`config-get checksum-mode`
    scanner_mode=`config-get scanner-mode`
    spare_policy=`config-get spare-policy`
    capacity_high_alert_threshold=`config-get capacity-high-alert-threshold`
    capacity_critical_alert_threshold=`config-get capacity-critical-alert-threshold`
    rfcache_devices=`config-get rfcache-devices`
    cached_storage_pools=`config-get cached-storage-pools`
    protection_domain_nodes=`config-get protection-domain-nodes`
    existing_cluster=`config-get existing-cluster`
    metadata_enabled=`config-get metadata-enabled`
    gateway_ip=`config-get gateway-ip`
    gateway_port=`config-get gateway-port`
    gateway_user=`config-get gateway-user`

    echo "---"
    echo "management_vip: $management_vip"
    echo "public_vip: $management_vip"
    echo "fuel_version: '6.1'"
    echo "nodes:"
    for node in ${!node_roles[*]}; do
        juju-log "NODE: $node, ${node_roles[$node]}"
        roles=(${node_roles[$node]})
        juju-log "ROLES: $roles, ${node_roles[$node]}"
        name=${node_names[$node]}

        for role in ${roles[*]}; do
            echo "- uid: '${node}'"
            echo "  role: ${role}"
            echo "  internal_address: ${node_ips[$node]}"
            echo "  storage_address: ${node_storage_ips[$node]}"
            echo "  name: ${name}"
        done
    done
    echo "scaleio:"
    echo "  storage_pools: $storage_pools"
    echo "  device_paths: $device_paths"
    echo "  protection_domain: $protection_domain"
    echo "  gateway_user: $gateway_user"
    echo "  gateway_port: $gateway_port"
    echo "  version: '2.0'"
    echo "  gateway_ip: $gateway_ip"
    echo "  gateway_password: $password"
    echo "  existing_storage_pools: default"
    echo "  existing_cluster: $existing_cluster"
    echo "  password: $password"
    echo "  sds_on_controller: $sds_on_controller"
    echo "  skip_checks: $skip_checks"
    echo "  zero_padding: $zero_padding"
    echo "  checksum_mode: $checksum_mode"
    echo "  scanner_mode: $scanner_mode"
    echo "  spare_policy: $spare_policy"
    echo "  capacity_high_alert_threshold: $capacity_high_alert_threshold"
    echo "  capacity_critical_alert_threshold: $capacity_critical_alert_threshold"
    echo "  rfcache_devices: $rfcache_devices"
    echo "  cached_storage_pools: $cached_storage_pools"
    echo "  protection_domain_nodes: $protection_domain_nodes"
    echo "  metadata:"
    echo "    plugin_id: 2"
    echo "    enabled: $metadata_enabled"
    echo "    toggleable: true"
    echo "    weight: 70"
    echo "    label: ScaleIOv2.0 plugin"
}
