#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "Fuel-master config changed"

manifests_path=`config-get manifests-path`
modules_path=`config-get modules-path`

rids=`relation-ids fuel-master`
if [ -n "$rids" ]; then
    node_yaml=`prepare_node_yaml`

    parse_tasks
    for rid in $rids; do
        relation-set -r $rid stage="${stages[0]}"
        for unit in `relation-list -r $rid` ; do
            cname=`convert-name $unit`
            relation-set -r $rid timestamp-$cname='0'
        done

        relation-set -r $rid node_yaml="$node_yaml"
        relation-set -r $rid facters="$facters"
        relation-set -r $rid modules_path="$modules_path"
        relation-set -r $rid manifests_path="$manifests_path"
    done
fi
