#!/bin/bash
my_dir="$(dirname "$0")"
. "$my_dir/common"

juju-log "Fuel-master relation triggered on master with remote: ${JUJU_REMOTE_UNIT}"

rids=`relation-ids fuel-master`
if [ -n "$rids" ]; then
    juju-log "Fuel-node $JUJU_REMOTE_UNIT is ready for the next stage"
    # collect timestamps from units
    declare -A timestamps=()
    for rid in $rids; do
        units=`relation-list -r $rid`
        for unit in $units ; do
            cname=`convert-name $unit`
            unit_timestamp=`relation-get -r $rid timestamp-$cname $unit`
            if [ -z "$unit_timestamp" ] ; then
                juju-log "Not ready to move to the next stage because of $cname doesn't have timestamp"
                exit
            fi
            timestamps[$cname]=$unit_timestamp
        done
    done

    # find max timestamp
    timestamp=0
    for cname in ${!timestamps[@]} ; do
        t=${timestamps[$cname]}
        if (( t > timestamp )) ; then
            timestamp=$t
        fi
    done
    # check that there is no units with smaller timestamp
    for cname in ${!timestamps[@]} ; do
        t=${timestamps[$cname]}
        if (( t < timestamp )) ; then
            juju-log "Not ready to move to the next stage because of $cname ($t < $timestamp)"
            exit
        fi
    done
    juju-log "All nodes are waiting for moving to next stage: $timestamp"

    parse_tasks
    if (( timestamp < stage_count )); then
        stage="${stages[$timestamp]}"
        juju-log "Moving to stage $timestamp - ${stages[$timestamp]}"
    else
        stage=""
        juju-log "Deployment finished"
    fi
    for rid in $rids; do
        # set timestamp back because unit doesn't see what it set
        for unit in `relation-list -r $rid` ; do
            cname=`convert-name $unit`
            relation-set -r $rid timestamp-$cname=$timestamp
        done
        relation-set -r $rid stage="$stage"
    done
fi
