#!/bin/bash

apt-get install -fy git

pushd /root
rm -rf fuel-plugin-scaleio
branch=`config-get branch-name`
git clone https://github.com/openstack/fuel-plugin-scaleio.git
cd fuel-plugin-scaleio
git checkout $branch
popd
